apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sangam-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abuabddullah/sangam_devops_part3_k8s
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
