apiVersion: apps/v1
kind: Deployment
metadata:
  name: sangam-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sangam-client
  template:
    metadata:
      labels:
        app: sangam-client
    spec:
      containers:
        - name: sangam-client
          image: abuabddullah/sangam-client:8e429a21d3f3f88a8b255ba03765ca8377959af3
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
