apiVersion: apps/v1
kind: Deployment
metadata:
  name: sangam-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sangam-mongo
  template:
    metadata:
      labels:
        app: sangam-mongo
    spec:
      containers:
        - name: sangam-mongo
          image: mongo:4.4
          ports:
            - containerPort: 27017
