apiVersion: apps/v1
kind: Deployment
metadata:
  name: sangam-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sangam-server
  template:
    metadata:
      labels:
        app: sangam-server
    spec:
      containers:
        - name: sangam-server
          image: abuabddullah/sangam-server:e1e64e0cb1ad77349cdd1e74d4d850d8d301fcfa
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              value: "mongodb://sangam-mongo-service:27017/sangamdb"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
