apiVersion: apps/v1
kind: Deployment
metadata:
  name: sangam-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sangam-server
  template:
    metadata:
      labels:
        app: sangam-server
    spec:
      containers:
        - name: sangam-server
          image: abuabddullah/sangam-server:a64eb010eeb4b4daa405f0e57e75c8ce70850533
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              value: "mongodb://sangam-mongo-service:27017/sangamdb"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
